name: Go

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Run Test
        id: tests
        run: |
          if go test -v ./...; then
            echo "result=âœ… Tests : rÃ©ussis" >> ]GITHUB_OUTPUT
            echo "tests=success"
          else
            echo "result=âŒ Tests : Ã©chouÃ©s" >> $GITHUB_OUTPUT
             echo "tests=failure"
            exit 1
          fi
    
      - name: code quality 
        id: lint
        run: |
          if curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin; then
            echo "result=âœ… Lint : c'est bo" >> $GITHUB_OUTPUT
            echo "lint=success"
          else
            echo "result=âŒ Lint : pas ouf" >> $GITHUB_OUTPUT
            echo "lint=failure"
            exit 1
          fi

      - name: Update README
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          STATUS_SECTION="## ðŸ“Š Statut du code\n\n${{ steps.tests.outputs.result }}  \n${{ steps.lint.outputs.result }}  \nðŸ•’ DerniÃ¨re vÃ©rification : $TIMESTAMP"

          # Remplace la section entre les balises <!--status-->...<!--endstatus-->
          sed -i '/<!--status-->/, /<!--endstatus-->/c\<!--status-->\n'"$STATUS_SECTION"'\n<!--endstatus-->' README.md

      - name: Commit README update
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add README.md
          git commit -m "auto: mise Ã  jour du statut du code" || echo "Pas de changements"
          git push

      - name: build app
        run: |
          go build -o app main.go
          echo "result=âœ… Build : rÃ©ussi" >> $GITHUB_OUTPUT
          echo "build=success"
